### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by ivaibhavjindal** [NJACKWinterOfCode/nwoc_algorithms#105]
The link to Substitution Cipher is broken in readme and newer inclusions are not present.

**Comment by ivaibhavjindal** [comment]
@Bhavnaharitsa I'd like to work on this.

**Comment by Bhavnaharitsa** [comment]
Go ahead!

**Comment by ivaibhavjindal** [comment]
Also I wanted to ask if i can add prims_algorithm.cpp and towerofhanoi.c in folders to make the repo look more cleaner and organised?

**Comment by Bhavnaharitsa** [comment]
I think we already have it
