### ISSUE TITLE
No Greedy Algorithms are present.

### ISSUE THREAD

**Issue by SubhradeepSS** [NJACKWinterOfCode/nwoc_algorithms#108]

**Comment by SubhradeepSS** [comment]
@Bhavnaharitsa please review it as valid issue

**Comment by Bhavnaharitsa** [comment]
Go ahead. Post a pr and I will review it

**Comment by SubhradeepSS** [comment]
> 
> 
> Go ahead. Post a pr and I will review it

Please update my score for raising the issue.

**Comment by SubhradeepSS** [comment]
@chanmol1999 @atm1504 I didn't get the point for raising the issue

**Comment by chanmol1999** [comment]
Okk I will update it @SubhradeepSS .
