### ISSUE TITLE
Add  Egyptian Fraction Greedy algorithm

### ISSUE THREAD

**Issue by parjanyaacoder** [NJACKWinterOfCode/nwoc_algorithms#113]
Egyptian Fraction algorithm needs to be added.If this is an valid issue I would like to work on this issue

**Comment by Bhavnaharitsa** [comment]
Go ahead. Use dynamic approach

**Comment by parjanyaacoder** [comment]
Can you guide me how to use dynamic approach

**Comment by Bhavnaharitsa** [comment]
Means you shouldn't give the input..get the input array from the user

**Comment by parjanyaacoder** [comment]
In this algorithm it is required to input only 2 numbers and not an array.So I have used dynamic approach only I have taken input from the user.So please review my pull request.
