### ISSUE TITLE
String Hashing applications.(C++)

### ISSUE THREAD

**Issue by ankitbaluni123** [NJACKWinterOfCode/nwoc_algorithms#51]
# Based on hash calculation of substring.
1. Pattern matching in a string in O(n) time (Rabin-Karp ).
2. Calculating the number of different substrings of a string in  O(n2 logn).
3. Finding all sub-palindromes in O(N) .

**Comment by sarthakeddy** [comment]
I want to contribute

**Comment by sarthakeddy** [comment]
Can you please help I am unable to push my commits. It is showing
Permission to NJACKWinterOfCode/nwoc_algorithms.git denied to sarthakeddy.

**Comment by sarthakeddy** [comment]
@ankitbaluni123  I have completed this issue and made the pull request too.
