### ISSUE TITLE
There are no algorithms on stacks.

### ISSUE THREAD

**Issue by hashtagaps** [NJACKWinterOfCode/nwoc_algorithms#56]
may I add some ?

**Comment by vishal-bhola** [comment]
I want to add some on this topic.

**Comment by vishal-bhola** [comment]
@Bhavnaharitsa  I have solved this issue and made a PR on this topic . Please review.

**Comment by Bhavnaharitsa** [comment]
mention the issue number

**Comment by hashtagaps** [comment]
Will add more .

**Comment by vanshita25** [comment]
i have added Tower of Hanoi

**Comment by vanshita25** [comment]
i have added tower of hanoi.
kindly review #64
