### ISSUE TITLE
Duplicate text in README.md

### ISSUE THREAD

**Issue by SubhradeepSS** [NJACKWinterOfCode/nwoc_algorithms#71]
@Bhavnaharitsa 
Can I remove the duplicate text from the README file?

**Comment by Bhavnaharitsa** [comment]
What duplicate texts?

**Comment by SubhradeepSS** [comment]
> What duplicate texts?

Sample algorithm
Sorting and String hashing algorithms are written separately as text and link:can be written once only like written under sample algorithm

**Comment by Bhavnaharitsa** [comment]
Okay, go ahead and change the link name under Bellman Ford equation too. Looks noob
