### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by abhisheknaiidu** [NJACKWinterOfCode/nwoc_algorithms#76]
It's not looking good. It needs to have some styling to make it attractive.

**Comment by Bhavnaharitsa** [comment]
What styling? Elaborate?

**Comment by abhisheknaiidu** [comment]
@Bhavnaharitsa I mean that it needs to be some-what attractive because everyone who visits this repo, will surely first check the README section only.

**Comment by Bhavnaharitsa** [comment]
Readme should contain all the information about the repo, need not be attractive.

**Comment by abhisheknaiidu** [comment]
@Bhavnaharitsa ohkk fine, as you wish so...

**Comment by Bhavnaharitsa** [comment]
If there are any missing information in Readme, go ahead else the focus should not be in making it decorative
