### ISSUE TITLE
Algorithm's should be in proper directory

### ISSUE THREAD

**Issue by axshivam** [NJACKWinterOfCode/nwoc_algorithms#92]

**Comment by Bhavnaharitsa** [comment]
What algorithm?

**Comment by MahmoudMabrok** [comment]
provide more explanation please @Shiv-sharma-111

**Comment by axshivam** [comment]
**Algorithms**--
```Searching```
```-------------->>binary_search.cpp```
```-------------->>linear_search.cpp```
```LinkedList```
 ```Sorting```
```.```
```.```
```.```
```.```
**README.md**
**instructions.md**

No any algorithm outside the [Algorithm's](https://github.com/NJACKWinterOfCode/nwoc_algorithms/tree/master/Algorithms) folder
